### ISSUE TITLE
PHP Fatal error:  Uncaught OutOfBoundsException: Cannot read 32-bit int, it exceeds the boundary of the file 

### ISSUE THREAD

**Issue by manishjesani912** [uro/teltonika-fm-parser#15]
Hello,

I am getting data from Teltonika FMB120.

PHP Fatal error:  Uncaught OutOfBoundsException: Cannot read 32-bit int, it exceeds the boundary of the file 

Please help me why this not decode.

Thanks.

**Comment by youb22** [comment]
Hi @manishjesani912,

Got the same error, it was due to the length of the data read.
In the main page example of the project, this is 1024 : 

```
// Read Data
$payload = fread($conn, 1024);
$packet = $parser->decodeData($payload);
```


But the frame from my FMM230 was bigger (1232 bytes).
I increased to 1500, it works now!

**Comment by devendar4b7** [comment]
PHP Fatal error:  Uncaught Error: Call to undefined function PhpBinaryReader\Type\bcadd() in /var/www/html/vendor/mdurrant/php-binary-reader/src/Type/Int64.php:43
Stack trace:
#0 /var/www/html/vendor/mdurrant/php-binary-reader/src/BinaryReader.php(236): PhpBinaryReader\Type\Int64->read()
#1 /var/www/html/vendor/uro/teltonika-fm-parser/src/Codec/BaseCodec.php(57): PhpBinaryReader\BinaryReader->readUInt64()
#2 /var/www/html/vendor/uro/teltonika-fm-parser/src/Codec/BaseCodec.php(31): Uro\TeltonikaFmParser\Codec\BaseCodec->decodeAvlData()
#3 /var/www/html/vendor/uro/teltonika-fm-parser/src/Protocol/Tcp/Decoder.php(51): Uro\TeltonikaFmParser\Codec\BaseCodec->decodeAvlDataCollection()
#4 /var/www/html/vendor/uro/teltonika-fm-parser/src/FmParser.php(37): Uro\TeltonikaFmParser\Protocol\Tcp\Decoder->decodeData()
#5 /var/www/html/index.php(94): Uro\TeltonikaFmParser\FmParser->decodeData()
#6 {main}
  thrown in /var/www/html/vendor/mdurrant/php-binary-reader/src/Type/Int64.php on line 43

**Comment by devendar4b7** [comment]
connection accepted!
PHP Fatal error:  Uncaught Error: Call to undefined function PhpBinaryReader\Type\bcadd() in /var/www/html/vendor/mdurrant/php-binary-reader/src/Type/Int64.php:43
Stack trace:
#0 /var/www/html/vendor/mdurrant/php-binary-reader/src/BinaryReader.php(236): PhpBinaryReader\Type\Int64->read()
#1 /var/www/html/vendor/uro/teltonika-fm-parser/src/Codec/BaseCodec.php(57): PhpBinaryReader\BinaryReader->readUInt64()
#2 /var/www/html/vendor/uro/teltonika-fm-parser/src/Codec/BaseCodec.php(31): Uro\TeltonikaFmParser\Codec\BaseCodec->decodeAvlData()
#3 /var/www/html/vendor/uro/teltonika-fm-parser/src/Protocol/Tcp/Decoder.php(51): Uro\TeltonikaFmParser\Codec\BaseCodec->decodeAvlDataCollection()
#4 /var/www/html/vendor/uro/teltonika-fm-parser/src/FmParser.php(37): Uro\TeltonikaFmParser\Protocol\Tcp\Decoder->decodeData()
#5 /var/www/html/index.php(94): Uro\TeltonikaFmParser\FmParser->decodeData()
#6 {main}
  thrown in /var/www/html/vendor/mdurrant/php-binary-reader/src/Type/Int64.php on line 43

**Comment by uro** [comment]
BCMATH
